services:
  - type: web
    name: image-to-text-ocr
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-khm
      pip install -r requirements.txt
    startCommand: bash start.sh
